//! Bit-exact verification of olorin's batched prompt-eval against llama.cpp.
//!
//! Run: cargo test --release --test gemma4_batch_verify -- --nocapture --test-threads=1
//!
//! Each test compares an olorin intermediate against a value captured from
//! llama-eval-callback dumps. Sums use f64 accumulation to avoid the f32
//! ordering trap that bit us in step6.

use std::path::Path;

fn model_path() -> String {
    let home = std::env::var("HOME").unwrap();
    format!("{home}/.olorin/models/gemma-4-e2b-it-Q4_K_M.gguf")
}

fn has_model() -> bool {
    Path::new(&model_path()).exists()
}

#[allow(dead_code)]
fn sum_f64(v: &[f32]) -> f64 {
    v.iter().map(|&x| x as f64).sum::<f64>()
}

#[test]
fn batch0_skeleton() {
    if !has_model() {
        eprintln!("SKIP: no model");
        return;
    }
    eprintln!("=== batch0: skeleton — no batched code yet ===");
    // Sanity: model can be loaded and forward_batch over [BOS] equals forward_one(BOS).
    let gguf = olorin::inference::gguf::GgufFile::open(Path::new(&model_path())).unwrap();
    let model = olorin::inference::engine::Gemma4Model::from_gguf(&gguf).unwrap();
    olorin::kernels::ffi::init().unwrap();
    let pool = olorin::inference::threadpool::ThreadPool::new();

    let mut a = olorin::inference::forward::Gemma4State::new(&model, 512, &pool);
    let logits_one = a.forward_one(&model, 2, &pool).to_vec();

    let mut b = olorin::inference::forward::Gemma4State::new(&model, 512, &pool);
    let logits_batch = b.forward_batch(&model, &[2u32], &pool).to_vec();

    assert_eq!(logits_one.len(), logits_batch.len());
    let max_abs_diff = logits_one
        .iter()
        .zip(logits_batch.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    eprintln!("max abs diff = {}", max_abs_diff);
    assert!(max_abs_diff < 1e-6, "skeleton forward_batch should equal forward_one for [BOS]");

    eprintln!("PASS: batch0");
}

// ---------------------------------------------------------------------------
// batch1: q4k_repack_8x8 byte-for-byte vs ggml golden fixture
// ---------------------------------------------------------------------------
//
// Fixtures live in tests/fixtures/q4k_repack/. They are generated by the
// one-shot tool in tools/q4k_repack_fixture/ which (a) extracts the first 16
// rows of blk.0.attn_output.weight from the gemma gguf and (b) runs a
// verbatim copy of ggml's make_block_q4_Kx8 + repack loop on the result.
//
// To regenerate:
//   tools/q4k_repack_fixture/regenerate.sh
//
// Reproduces ggml v6+ behaviour. If ggml ever changes its repack layout,
// regenerate the fixture and bump the research note.

const FIX_NROWS: usize = 16;
const FIX_NCOLS: usize = 1536; // gemma E2B hidden_dim
const FIX_ROW_BYTES: usize = (FIX_NCOLS / 256) * 144; // 864
const FIX_TOTAL: usize = FIX_NROWS * FIX_ROW_BYTES;

fn fixture_path(name: &str) -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/q4k_repack");
    p.push(name);
    p
}

/// One-shot helper. Run with:
///   cargo test --release --test gemma4_batch_verify -- --ignored --nocapture extract_q4k_input
/// This dumps the first 16 rows of blk.0.attn_output.weight to
/// tests/fixtures/q4k_repack/input.bin so the C generator can produce golden.bin.
#[test]
#[ignore]
fn extract_q4k_input_fixture() {
    if !has_model() {
        panic!("no model — cannot extract fixture");
    }
    let gguf = olorin::inference::gguf::GgufFile::open(Path::new(&model_path())).unwrap();
    let model = olorin::inference::engine::Gemma4Model::from_gguf(&gguf).unwrap();
    olorin::kernels::ffi::init().unwrap();

    // Find a layer-0 weight tensor that is Q4K-typed in this quant. Different
    // gemma .gguf quants put Q4K on different tensors; print everything and
    // pick the first match. n_cols must be hidden_dim (= 1536 for E2B) so
    // row_bytes = 6*144 = 864 — that constrains us to ffn_down (which has
    // ne[0]=ffn_dim=6144, not what we want) or attn_q/k/v/o (ne[0]=hidden_dim).
    let lw = &model.layers[0];
    eprintln!(
        "[fixture] layer 0 dtypes: wq={} wk={} wv={} wo={} gate={} up={} down={}",
        lw.wq_dtype, lw.wk_dtype, lw.wv_dtype, lw.wo_dtype,
        lw.w_gate_dtype, lw.w_up_dtype, lw.w_down_dtype
    );
    let q4k = olorin::inference::matmul::GGML_TYPE_Q4_K;
    // Pick the first attn projection that's Q4K. wq/wk/wv/wo all have
    // n_cols = hidden_dim, so the row layout matches FIX_NCOLS=1536.
    let (ptr, label): (*const u8, &str) = if lw.wq_dtype == q4k {
        (lw.wq, "wq")
    } else if lw.wk_dtype == q4k {
        (lw.wk, "wk")
    } else if lw.wv_dtype == q4k {
        (lw.wv, "wv")
    } else if lw.wo_dtype == q4k {
        (lw.wo, "wo")
    } else {
        // Fallback: scan later layers' wq.
        let mut found: Option<(*const u8, &str)> = None;
        for (i, l) in model.layers.iter().enumerate().skip(1) {
            if l.wq_dtype == q4k {
                eprintln!("[fixture] using layer {} wq (no Q4K in layer 0)", i);
                found = Some((l.wq, "wq_lN"));
                break;
            }
        }
        found.expect("no Q4K attn weight found in any layer")
    };
    eprintln!("[fixture] using layer 0 {label}");
    assert_eq!(model.hidden_dim, FIX_NCOLS, "fixture assumed hidden_dim={FIX_NCOLS}");

    // Q4K storage is contiguous: each output row has n_cols/256 blocks of
    // 144 bytes, packed back-to-back. Take the first 16 rows.
    let bytes: &[u8] = unsafe { std::slice::from_raw_parts(ptr, FIX_TOTAL) };

    let path = fixture_path("input.bin");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, bytes).unwrap();
    eprintln!("wrote {} bytes to {}", bytes.len(), path.display());
}

#[test]
fn batch1_repack_q4k_bytes_match_ggml_golden() {
    let input_path = fixture_path("input.bin");
    let golden_path = fixture_path("golden.bin");
    if !input_path.exists() || !golden_path.exists() {
        eprintln!(
            "SKIP: missing fixtures at {} — run tools/q4k_repack_fixture/regenerate.sh",
            input_path.parent().unwrap().display()
        );
        return;
    }
    olorin::kernels::ffi::init().unwrap();

    let input = std::fs::read(&input_path).unwrap();
    let golden = std::fs::read(&golden_path).unwrap();
    assert_eq!(input.len(), FIX_TOTAL, "input.bin wrong size");
    assert_eq!(golden.len(), FIX_TOTAL, "golden.bin wrong size");

    let mut olorin_out = vec![0u8; FIX_TOTAL];
    unsafe {
        olorin::kernels::ffi_inference::q4k_repack_8x8(
            input.as_ptr(),
            olorin_out.as_mut_ptr(),
            FIX_NROWS as i32,
            FIX_NCOLS as i32,
        );
    }

    if let Some(idx) = olorin_out.iter().zip(&golden).position(|(a, b)| a != b) {
        let lo = idx.saturating_sub(8);
        let hi = (idx + 8).min(FIX_TOTAL);
        eprintln!("first diff at byte {idx}");
        eprintln!("olorin: {:02x?}", &olorin_out[lo..hi]);
        eprintln!("ggml:   {:02x?}", &golden[lo..hi]);
        panic!("repack mismatch vs ggml golden");
    }
    eprintln!("PASS: batch1 — {} bytes match", FIX_TOTAL);
}
