//! Bit-exact verification of olorin's batched prompt-eval against llama.cpp.
//!
//! Run: cargo test --release --test gemma4_batch_verify -- --nocapture --test-threads=1
//!
//! Each test compares an olorin intermediate against a value captured from
//! llama-eval-callback dumps. Sums use f64 accumulation to avoid the f32
//! ordering trap that bit us in step6.

use std::path::Path;

fn model_path() -> String {
    let home = std::env::var("HOME").unwrap();
    format!("{home}/.olorin/models/gemma-4-e2b-it-Q4_K_M.gguf")
}

fn has_model() -> bool {
    Path::new(&model_path()).exists()
}

#[allow(dead_code)]
fn sum_f64(v: &[f32]) -> f64 {
    v.iter().map(|&x| x as f64).sum::<f64>()
}

#[test]
fn batch0_skeleton() {
    if !has_model() {
        eprintln!("SKIP: no model");
        return;
    }
    eprintln!("=== batch0: skeleton — no batched code yet ===");
    // Sanity: model can be loaded and forward_batch over [BOS] equals forward_one(BOS).
    let gguf = olorin::inference::gguf::GgufFile::open(Path::new(&model_path())).unwrap();
    let model = olorin::inference::engine::Gemma4Model::from_gguf(&gguf).unwrap();
    olorin::kernels::ffi::init().unwrap();
    let pool = olorin::inference::threadpool::ThreadPool::new();

    let mut a = olorin::inference::forward::Gemma4State::new(&model, 512, &pool);
    let logits_one = a.forward_one(&model, 2, &pool).to_vec();

    let mut b = olorin::inference::forward::Gemma4State::new(&model, 512, &pool);
    let logits_batch = b.forward_batch(&model, &[2u32], &pool).to_vec();

    assert_eq!(logits_one.len(), logits_batch.len());
    let max_abs_diff = logits_one
        .iter()
        .zip(logits_batch.iter())
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    eprintln!("max abs diff = {}", max_abs_diff);
    assert!(max_abs_diff < 1e-6, "skeleton forward_batch should equal forward_one for [BOS]");

    eprintln!("PASS: batch0");
}

// ---------------------------------------------------------------------------
// batch1: q4k_repack_8x8 byte-for-byte vs ggml golden fixture
// ---------------------------------------------------------------------------
//
// Fixtures live in tests/fixtures/q4k_repack/. They are generated by the
// one-shot tool in tools/q4k_repack_fixture/ which (a) extracts the first 16
// rows of blk.0.attn_output.weight from the gemma gguf and (b) runs a
// verbatim copy of ggml's make_block_q4_Kx8 + repack loop on the result.
//
// To regenerate:
//   tools/q4k_repack_fixture/regenerate.sh
//
// Reproduces ggml v6+ behaviour. If ggml ever changes its repack layout,
// regenerate the fixture and bump the research note.

const FIX_NROWS: usize = 16;
const FIX_NCOLS: usize = 1536; // gemma E2B hidden_dim
const FIX_ROW_BYTES: usize = (FIX_NCOLS / 256) * 144; // 864
const FIX_TOTAL: usize = FIX_NROWS * FIX_ROW_BYTES;

fn fixture_path(name: &str) -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests/fixtures/q4k_repack");
    p.push(name);
    p
}

/// One-shot helper. Run with:
///   cargo test --release --test gemma4_batch_verify -- --ignored --nocapture extract_q4k_input
/// This dumps the first 16 rows of blk.0.attn_output.weight to
/// tests/fixtures/q4k_repack/input.bin so the C generator can produce golden.bin.
#[test]
#[ignore]
fn extract_q4k_input_fixture() {
    if !has_model() {
        panic!("no model — cannot extract fixture");
    }
    let gguf = olorin::inference::gguf::GgufFile::open(Path::new(&model_path())).unwrap();
    let model = olorin::inference::engine::Gemma4Model::from_gguf(&gguf).unwrap();
    olorin::kernels::ffi::init().unwrap();

    // Find a layer-0 weight tensor that is Q4K-typed in this quant. Different
    // gemma .gguf quants put Q4K on different tensors; print everything and
    // pick the first match. n_cols must be hidden_dim (= 1536 for E2B) so
    // row_bytes = 6*144 = 864 — that constrains us to ffn_down (which has
    // ne[0]=ffn_dim=6144, not what we want) or attn_q/k/v/o (ne[0]=hidden_dim).
    let lw = &model.layers[0];
    eprintln!(
        "[fixture] layer 0 dtypes: wq={} wk={} wv={} wo={} gate={} up={} down={}",
        lw.wq_dtype, lw.wk_dtype, lw.wv_dtype, lw.wo_dtype,
        lw.w_gate_dtype, lw.w_up_dtype, lw.w_down_dtype
    );
    let q4k = olorin::inference::matmul::GGML_TYPE_Q4_K;
    // Pick the first attn projection that's Q4K. wq/wk/wv/wo all have
    // n_cols = hidden_dim, so the row layout matches FIX_NCOLS=1536.
    let (ptr, label): (*const u8, &str) = if lw.wq_dtype == q4k {
        (lw.wq, "wq")
    } else if lw.wk_dtype == q4k {
        (lw.wk, "wk")
    } else if lw.wv_dtype == q4k {
        (lw.wv, "wv")
    } else if lw.wo_dtype == q4k {
        (lw.wo, "wo")
    } else {
        // Fallback: scan later layers' wq.
        let mut found: Option<(*const u8, &str)> = None;
        for (i, l) in model.layers.iter().enumerate().skip(1) {
            if l.wq_dtype == q4k {
                eprintln!("[fixture] using layer {} wq (no Q4K in layer 0)", i);
                found = Some((l.wq, "wq_lN"));
                break;
            }
        }
        found.expect("no Q4K attn weight found in any layer")
    };
    eprintln!("[fixture] using layer 0 {label}");
    assert_eq!(model.hidden_dim, FIX_NCOLS, "fixture assumed hidden_dim={FIX_NCOLS}");

    // Q4K storage is contiguous: each output row has n_cols/256 blocks of
    // 144 bytes, packed back-to-back. Take the first 16 rows.
    let bytes: &[u8] = unsafe { std::slice::from_raw_parts(ptr, FIX_TOTAL) };

    let path = fixture_path("input.bin");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, bytes).unwrap();
    eprintln!("wrote {} bytes to {}", bytes.len(), path.display());
}

#[test]
fn batch1_repack_q4k_bytes_match_ggml_golden() {
    let input_path = fixture_path("input.bin");
    let golden_path = fixture_path("golden.bin");
    if !input_path.exists() || !golden_path.exists() {
        eprintln!(
            "SKIP: missing fixtures at {} — run tools/q4k_repack_fixture/regenerate.sh",
            input_path.parent().unwrap().display()
        );
        return;
    }
    olorin::kernels::ffi::init().unwrap();

    let input = std::fs::read(&input_path).unwrap();
    let golden = std::fs::read(&golden_path).unwrap();
    assert_eq!(input.len(), FIX_TOTAL, "input.bin wrong size");
    assert_eq!(golden.len(), FIX_TOTAL, "golden.bin wrong size");

    let mut olorin_out = vec![0u8; FIX_TOTAL];
    unsafe {
        olorin::kernels::ffi_inference::q4k_repack_8x8(
            input.as_ptr(),
            olorin_out.as_mut_ptr(),
            FIX_NROWS as i32,
            FIX_NCOLS as i32,
        );
    }

    if let Some(idx) = olorin_out.iter().zip(&golden).position(|(a, b)| a != b) {
        let lo = idx.saturating_sub(8);
        let hi = (idx + 8).min(FIX_TOTAL);
        eprintln!("first diff at byte {idx}");
        eprintln!("olorin: {:02x?}", &olorin_out[lo..hi]);
        eprintln!("ggml:   {:02x?}", &golden[lo..hi]);
        panic!("repack mismatch vs ggml golden");
    }
    eprintln!("PASS: batch1 — {} bytes match", FIX_TOTAL);
}

// ---------------------------------------------------------------------------
// batch2: q4k_8x8_q8k_matvec bit-exact vs olorin's existing q4k_matvec
// ---------------------------------------------------------------------------
//
// The new q4k_8x8_q8k_matvec targets ggml's 8x8 gemm f32 reduction order
// (per-sb FMAs per block, mins accumulated in a parallel register,
// subtracted once after the b loop — see
// docs/superpowers/research/2026-04-08-ggml-q4k-8x8-q8k-gemm.md). Olorin's
// existing q4k_matvec uses a different per-block order (one f32 add +
// mins subtract per block), so the two are NOT f32-bit-equal even for N=1
// — they differ in the low bits of the f32 rounding.
//
// Bit-exact validation vs ggml's 8x8 gemm happens in Task 10 via a golden
// fixture (same pattern as Task 6). Here we use a tight absolute tolerance
// (1e-4) that catches algorithm bugs but accepts f32 reduction-order drift.
//
// Weight choice: layer 0 ffn_gate.weight — shape [hidden_dim, ffn_dim] =
// [1536, 6144]. It's Q4K-typed in the Q4_K_M quant (layer 0 dtypes were
// wq=14 wk=13 wv=14 wo=13 gate=12 up=12 down=14, i.e. only gate/up are Q4K).
// Storage: n_rows=ffn_dim=6144 (outer), n_cols=hidden_dim=1536 (inner).
// Both divisible by 8 and 256 respectively. ✓

#[test]
fn batch2_q4k_8x8_q8k_matvec_bitexact_vs_existing_matvec() {
    if !has_model() { eprintln!("SKIP: no model"); return; }
    let gguf = olorin::inference::gguf::GgufFile::open(Path::new(&model_path())).unwrap();
    let model = olorin::inference::engine::Gemma4Model::from_gguf(&gguf).unwrap();
    olorin::kernels::ffi::init().unwrap();

    let lw = &model.layers[0];
    let q4k = olorin::inference::matmul::GGML_TYPE_Q4_K;
    assert_eq!(lw.w_gate_dtype, q4k, "blk.0.ffn_gate.weight must be Q4K");

    let n_rows = model.ffn_dim[0];      // 6144
    let n_cols = model.hidden_dim;      // 1536
    assert!(n_rows % 8 == 0);
    assert!(n_cols % 256 == 0);

    // Deterministic input
    let mut x = vec![0.0f32; n_cols];
    for i in 0..n_cols {
        x[i] = ((i as f32) * 0.0137 - 0.5).sin() * 0.3;
    }

    // Quantize input to Q8K
    let n_blocks = n_cols / 256;
    let mut q8_qs = vec![0i8; n_cols + 12];
    let mut q8_d = vec![0.0f32; n_blocks];
    let mut q8_bsums = vec![0i16; n_blocks * 16];
    olorin::inference::matmul::quant_input(&x, &mut q8_qs, &mut q8_d, &mut q8_bsums);

    // Reference: olorin's existing Q4K matvec on the raw (non-repacked) weight
    let mut ref_out = vec![0.0f32; n_rows];
    olorin::inference::matmul::q4k_matvec(
        lw.w_gate,
        &q8_qs, &q8_d, &q8_bsums,
        &mut ref_out,
        n_rows, n_cols,
    );

    // New path: repack the weight, then 8x8 matvec
    let row_bytes = n_blocks * 144;
    let mut packed = vec![0u8; n_rows * row_bytes];
    unsafe {
        olorin::kernels::ffi_inference::q4k_repack_8x8(
            lw.w_gate, packed.as_mut_ptr(), n_rows as i32, n_cols as i32,
        );
    }
    let mut new_out = vec![0.0f32; n_rows];
    let mut scratch = vec![0u8; 144];
    let pow2 = olorin::inference::matmul::pow2_table();
    unsafe {
        olorin::kernels::ffi_inference::q4k_8x8_q8k_matvec(
            packed.as_ptr(),
            q8_qs.as_ptr(),
            q8_d.as_ptr(),
            q8_bsums.as_ptr(),
            pow2.as_ptr(),
            scratch.as_mut_ptr(),
            new_out.as_mut_ptr(),
            n_rows as i32, n_cols as i32,
        );
    }

    // Tolerance-based comparison (see header comment for rationale).
    const EPS: f32 = 1.0e-4;
    let mut max_abs_diff = 0.0f32;
    let mut worst_row = 0usize;
    for i in 0..n_rows {
        let d = (ref_out[i] - new_out[i]).abs();
        if d > max_abs_diff {
            max_abs_diff = d;
            worst_row = i;
        }
    }
    if max_abs_diff > EPS {
        let lo = worst_row.saturating_sub(4);
        let hi = (worst_row + 4).min(n_rows);
        eprintln!("worst row {worst_row}: |ref - new| = {max_abs_diff:e} > {EPS:e}");
        eprintln!("ref:  {:?}", &ref_out[lo..hi]);
        eprintln!("new:  {:?}", &new_out[lo..hi]);
        panic!("q4k_8x8_q8k_matvec diverges from reference matvec beyond tolerance");
    }
    eprintln!(
        "PASS: batch2 — {} rows, max |ref - new| = {max_abs_diff:e}",
        n_rows
    );
}

// ---------------------------------------------------------------------------
// batch3: q4k_8x8_q8k_gemm bit-exact per-column vs looped matvec
// ---------------------------------------------------------------------------
//
// Run the gemm for N input columns and compare each output column byte-for-byte
// to running the matvec once per column. Per-column f32 reduction order is
// identical (the gemm just shares the per-(tile,row,block) unpack + scale
// extraction across the N columns), so every output bit must match.

#[test]
fn batch3_q4k_8x8_q8k_gemm_bitexact_per_column() {
    if !has_model() { eprintln!("SKIP: no model"); return; }
    let gguf = olorin::inference::gguf::GgufFile::open(Path::new(&model_path())).unwrap();
    let model = olorin::inference::engine::Gemma4Model::from_gguf(&gguf).unwrap();
    olorin::kernels::ffi::init().unwrap();

    // Same weight pick as batch2: layer 0 ffn_gate (Q4K in Q4_K_M quant).
    let lw = &model.layers[0];
    assert_eq!(lw.w_gate_dtype, olorin::inference::matmul::GGML_TYPE_Q4_K);
    let n_rows = model.ffn_dim[0];        // 6144
    let n_cols = model.hidden_dim;        // 1536
    let n_blocks = n_cols / 256;
    let row_bytes = n_blocks * 144;

    // Repack the weight once.
    let mut packed = vec![0u8; n_rows * row_bytes];
    unsafe {
        olorin::kernels::ffi_inference::q4k_repack_8x8(
            lw.w_gate, packed.as_mut_ptr(), n_rows as i32, n_cols as i32,
        );
    }

    let pow2 = olorin::inference::matmul::pow2_table();

    for &n in &[2usize, 8usize] {
        // Build N deterministic input columns.
        let mut x = vec![0.0f32; n_cols * n];
        for k in 0..n {
            for i in 0..n_cols {
                x[k * n_cols + i] = (((i + k * 7) as f32) * 0.0137 - 0.5).cos() * 0.4;
            }
        }
        // Quantize each column independently to Q8K.
        let qs_stride = n_cols + 12;
        let mut q8_qs = vec![0i8; qs_stride * n];
        let mut q8_d = vec![0.0f32; n_blocks * n];
        let mut q8_bsums = vec![0i16; n_blocks * 16 * n];
        for k in 0..n {
            olorin::inference::matmul::quant_input(
                &x[k * n_cols..(k + 1) * n_cols],
                &mut q8_qs[k * qs_stride..(k + 1) * qs_stride],
                &mut q8_d[k * n_blocks..(k + 1) * n_blocks],
                &mut q8_bsums[k * n_blocks * 16..(k + 1) * n_blocks * 16],
            );
        }

        // Reference: N matvec calls, one per column.
        let mut ref_out = vec![0.0f32; n_rows * n];
        let mut scratch = vec![0u8; 144];
        for k in 0..n {
            unsafe {
                olorin::kernels::ffi_inference::q4k_8x8_q8k_matvec(
                    packed.as_ptr(),
                    q8_qs[k * qs_stride..].as_ptr(),
                    q8_d[k * n_blocks..].as_ptr(),
                    q8_bsums[k * n_blocks * 16..].as_ptr(),
                    pow2.as_ptr(),
                    scratch.as_mut_ptr(),
                    ref_out[k * n_rows..].as_mut_ptr(),
                    n_rows as i32, n_cols as i32,
                );
            }
        }

        // New: gemm in one call.
        let mut new_out = vec![0.0f32; n_rows * n];
        let mut acc_scratch = vec![0.0f32; 2 * n];
        unsafe {
            olorin::kernels::ffi_inference::q4k_8x8_q8k_gemm(
                packed.as_ptr(),
                q8_qs.as_ptr(),
                q8_d.as_ptr(),
                q8_bsums.as_ptr(),
                pow2.as_ptr(),
                scratch.as_mut_ptr(),
                acc_scratch.as_mut_ptr(),
                new_out.as_mut_ptr(),
                n_rows as i32, n_cols as i32, n as i32,
            );
        }

        // Bit-exact comparison.
        let mut first_mismatch: Option<usize> = None;
        let mut max_abs_diff = 0.0f32;
        for i in 0..(n_rows * n) {
            if ref_out[i].to_bits() != new_out[i].to_bits() {
                if first_mismatch.is_none() { first_mismatch = Some(i); }
                let d = (ref_out[i] - new_out[i]).abs();
                if d > max_abs_diff { max_abs_diff = d; }
            }
        }
        if let Some(idx) = first_mismatch {
            let col = idx / n_rows;
            let row = idx % n_rows;
            eprintln!(
                "N={n}: first mismatch col={col} row={row} ref=0x{:08x} new=0x{:08x} max_abs_diff={max_abs_diff:e}",
                ref_out[idx].to_bits(),
                new_out[idx].to_bits(),
            );
            panic!("q4k_8x8_q8k_gemm diverges from looped matvec (must be bit-exact per column)");
        }
        eprintln!("PASS: batch3 N={n} — {} outputs bit-exact", n_rows * n);
    }
}
