//! report — self-contained HTML report renderer, the fourth consumer of
//! the RuneOutput v1 contract (REPL text, web chart, `--json`, this).
//!
//! One .html file, inline CSS, inline SVG, zero external assets, zero
//! JavaScript — it opens anywhere, prints cleanly, and survives being
//! emailed. Charts consume the same `col_reduce`-kernel-reduced column
//! envelope as the block-bar renderer (`plot::columnize`), so every
//! presentation surface agrees about the data.
//!
//! Deliberately deterministic: no wall-clock timestamp, no model
//! narration — same inputs produce the same bytes, so reports golden-
//! test like every other rune output. Every file-derived string is
//! HTML-escaped.

use super::output::RuneOutput;
use super::plot;

/// One analyzed file: the friendly name, the rune that ran, its output.
pub struct ReportSection {
    pub display: String,
    pub rune:    String,
    pub output:  RuneOutput,
}

const CSS: &str = "\
body{font:15px/1.5 -apple-system,'Segoe UI',Roboto,sans-serif;color:#1a2233;\
margin:0;background:#f4f6f9}main{max-width:760px;margin:0 auto;padding:24px}\
h1{font-size:21px;margin:0 0 2px}h2{font-size:16px;margin:26px 0 8px}\
.sub{color:#5a6478;font-size:13px;margin-bottom:18px}\
.findings{background:#0e2a47;color:#eaf2fb;border-radius:8px;padding:14px 18px;\
margin:18px 0}.findings h2{margin:0 0 8px;color:#9fc6ef;font-size:13px;\
text-transform:uppercase;letter-spacing:.08em}.findings p{margin:4px 0;\
font-size:15px}.findings .score{color:#9fc6ef;font-size:13px}\
section{background:#fff;border:1px solid #dde3ec;border-radius:8px;\
padding:14px 18px;margin:14px 0}section h2{margin-top:0}\
.rune{color:#5a6478;font-weight:400;font-size:13px}\
table{border-collapse:collapse;font-size:13px;margin:8px 0}\
td,th{padding:2px 14px 2px 0;text-align:left;vertical-align:top}\
th{color:#5a6478;font-weight:600}\
.num{font-variant-numeric:tabular-nums}\
.anom{color:#a33;font-size:13px;margin:2px 0}\
svg{display:block;margin:10px 0}\
footer{color:#5a6478;font-size:12px;margin:22px 0 8px}\
footer a{color:#2a6dad}";

/// Render the full report. `correlation` is the eacorrelate output when
/// two or more files were analyzed together; `version` is the olorin
/// version string baked into the footer (passed in so tests can pin it).
pub fn render_report(
    sections: &[ReportSection],
    correlation: Option<&RuneOutput>,
    version: &str,
) -> String {
    let title = match sections.len() {
        0 => "Olorin report".to_string(),
        1 => format!("Olorin report — {}", esc(&sections[0].display)),
        n => format!("Olorin report — {n} files"),
    };

    let mut h = String::with_capacity(16 * 1024);
    h.push_str("<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n");
    h.push_str(&format!("<title>{title}</title>\n<style>{CSS}</style></head>\n<body><main>\n"));
    h.push_str(&format!("<h1>{title}</h1>\n"));
    let names: Vec<String> = sections.iter().map(|s| esc(&s.display)).collect();
    h.push_str(&format!(
        "<div class=\"sub\">deterministic SIMD analysis of {}</div>\n",
        names.join(", "),
    ));

    if let Some(corr) = correlation {
        h.push_str(&findings_banner(corr));
    }
    for s in sections {
        h.push_str(&section_html(s));
    }

    let total_scan: u64 = sections.iter().map(|s| s.output.totals.scan_us).sum::<u64>()
        + correlation.map_or(0, |c| c.totals.scan_us);
    h.push_str(&format!(
        "<footer>generated by <a href=\"https://github.com/petlukk/Olorin\">olorin</a> \
         {} &middot; {} &micro;s of SIMD scan &middot; no data left this machine</footer>\n",
        esc(version), total_scan,
    ));
    h.push_str("</main></body></html>\n");
    h
}

/// The conclusion, before the evidence — mirrors the narration ordering.
fn findings_banner(corr: &RuneOutput) -> String {
    if corr.correlations.is_empty() {
        return String::new();
    }
    let mut b = String::from("<div class=\"findings\"><h2>Cross-file correlations</h2>\n");
    for c in &corr.correlations {
        b.push_str(&format!(
            "<p><strong>{}</strong> follows <strong>{}</strong> by +{}&thinsp;s \
             <span class=\"score\">(r={:.2}, peak {}, resolution {}&thinsp;s)</span></p>\n",
            esc(&c.stream_a), esc(&c.stream_b), c.lag_seconds,
            c.score, esc(&c.peak_bucket), c.width_seconds,
        ));
    }
    b.push_str("</div>\n");
    b
}

fn section_html(s: &ReportSection) -> String {
    let out = &s.output;
    let mut h = format!(
        "<section><h2>{} <span class=\"rune\">via {}</span></h2>\n",
        esc(&s.display), esc(&s.rune),
    );
    if let Some(err) = &out.error {
        h.push_str(&format!("<p class=\"anom\">{}</p>\n</section>\n", esc(err)));
        return h;
    }

    h.push_str("<table>");
    if let Some(src) = &out.source {
        h.push_str(&format!(
            "<tr><th>format</th><td>{}</td><th>bytes</th><td class=\"num\">{}</td></tr>",
            esc(&src.format), src.bytes,
        ));
    }
    h.push_str(&format!(
        "<tr><th>records</th><td class=\"num\">{}</td><th>scan</th>\
         <td class=\"num\">{} &micro;s</td></tr></table>\n",
        out.totals.rows, out.totals.scan_us,
    ));

    if let Some(svg) = svg_chart(out) {
        h.push_str(&svg);
    } else if !out.categories.is_empty() {
        h.push_str(&categories_table(out));
    }
    h.push_str(&fields_table(out));

    for a in &out.anomalies {
        let ratio = if a.ratio.is_finite() {
            format!("{:.1}×", a.ratio)
        } else {
            "∞".to_string()
        };
        h.push_str(&format!(
            "<p class=\"anom\">spike at {} — count {} ({ratio} baseline {:.0})</p>\n",
            esc(&a.bucket), a.count, a.baseline,
        ));
    }
    h.push_str("</section>\n");
    h
}

/// Non-series categories (severity ladders, hour buckets) as a table,
/// capped so a wide categorical field can't bloat the report.
fn categories_table(out: &RuneOutput) -> String {
    const CAP: usize = 12;
    let mut t = String::from("<table><tr><th>bucket</th><th>count</th></tr>");
    for c in out.categories.iter().take(CAP) {
        t.push_str(&format!(
            "<tr><td>{}</td><td class=\"num\">{}</td></tr>",
            esc(&c.name), c.count,
        ));
    }
    if out.categories.len() > CAP {
        t.push_str(&format!(
            "<tr><td colspan=\"2\">… {} more</td></tr>",
            out.categories.len() - CAP,
        ));
    }
    t.push_str("</table>\n");
    t
}

fn fields_table(out: &RuneOutput) -> String {
    if out.fields.is_empty() {
        return String::new();
    }
    let mut t = String::from(
        "<table><tr><th>field</th><th>kind</th><th>count</th><th>summary</th></tr>",
    );
    for f in &out.fields {
        let summary = if let Some(n) = &f.numeric {
            format!("min {} · max {} · mean {:.4}", fnum(n.min), fnum(n.max), n.mean)
        } else if let Some(tx) = &f.text {
            let tops: Vec<String> = tx.top.iter().take(3).map(|e| esc(&e.value)).collect();
            format!("{} unique · top: {}", tx.unique, tops.join(", "))
        } else if let Some(b) = &f.bool {
            format!("true {} · false {}", b.true_count, b.false_count)
        } else if let Some(ts) = &f.timestamp {
            format!("{} .. {}", esc(&ts.min), esc(&ts.max))
        } else {
            String::new()
        };
        t.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td class=\"num\">{}</td><td>{summary}</td></tr>",
            esc(&f.name), f.kind.as_str(), f.count,
        ));
    }
    t.push_str("</table>\n");
    t
}

/// Trim trailing zeros from a stat so the table reads `42` not `42.0000`.
fn fnum(v: f64) -> String {
    if v == v.trunc() && v.abs() < 1e15 {
        format!("{}", v as i64)
    } else {
        format!("{v:.4}")
    }
}

// ── SVG chart ────────────────────────────────────────────────────────────────

const SVG_W: f32 = 720.0;
const SVG_H: f32 = 200.0;
const PAD_L: f32 = 46.0; // y labels
const PAD_B: f32 = 22.0; // x labels
const PAD_T: f32 = 8.0;

/// Inline SVG bar chart for a chronological series, or None when the
/// output isn't one. Same series test as `chart_for` (ISO labels carry a
/// 'T'); same `col_reduce` reduction and spike flags as the block bars.
pub fn svg_chart(out: &RuneOutput) -> Option<String> {
    let is_series = out.categories.first().is_some_and(|c| c.name.contains('T'));
    if !is_series || out.categories.len() < 2 {
        return None;
    }
    let counts: Vec<f32> = out.categories.iter().map(|c| c.count as f32).collect();
    let n_src = counts.len();
    let cols = 120usize.min(n_src);
    let heights = plot::columnize(&counts, cols);
    let spike_src = plot::spike_flags(out);
    let spike: Vec<bool> = (0..cols)
        .map(|c| {
            let lo = (c * n_src) / cols;
            let hi = ((c + 1) * n_src) / cols;
            spike_src[lo..hi].iter().any(|&f| f)
        })
        .collect();
    let ceil = plot::nice_ceil(heights.iter().copied().fold(0.0, f32::max));
    let median = out
        .anomalies
        .first()
        .map(|a| a.baseline as f32)
        .unwrap_or_else(|| plot::robust_median(&counts));

    let plot_w = SVG_W - PAD_L - 8.0;
    let plot_h = SVG_H - PAD_T - PAD_B;
    let y = |v: f32| PAD_T + plot_h * (1.0 - (v / ceil).min(1.0));
    let bw = plot_w / cols as f32;

    let mut s = format!(
        "<svg viewBox=\"0 0 {SVG_W} {SVG_H}\" width=\"{SVG_W}\" \
         xmlns=\"http://www.w3.org/2000/svg\" role=\"img\">\n",
    );
    // y axis: ceiling gridline + zero baseline + labels
    for (v, label) in [(ceil, true), (0.0, false)] {
        let yy = y(v);
        s.push_str(&format!(
            "<line x1=\"{PAD_L}\" y1=\"{yy:.1}\" x2=\"{:.1}\" y2=\"{yy:.1}\" \
             stroke=\"#dde3ec\" stroke-width=\"1\"/>\n",
            PAD_L + plot_w,
        ));
        let text = if label { fnum(ceil as f64) } else { "0".to_string() };
        s.push_str(&format!(
            "<text x=\"{:.1}\" y=\"{:.1}\" text-anchor=\"end\" \
             font-size=\"11\" fill=\"#5a6478\">{text}</text>\n",
            PAD_L - 6.0, yy + 4.0,
        ));
    }
    // bars
    for (i, &hgt) in heights.iter().enumerate() {
        if hgt <= 0.0 {
            continue;
        }
        let x = PAD_L + i as f32 * bw;
        let top = y(hgt);
        let fill = if spike[i] { "#c0392b" } else { "#3a76b0" };
        s.push_str(&format!(
            "<rect x=\"{x:.1}\" y=\"{top:.1}\" width=\"{:.2}\" height=\"{:.1}\" \
             fill=\"{fill}\"/>\n",
            (bw - 0.6).max(0.4),
            y(0.0) - top,
        ));
    }
    // median baseline
    if median > 0.0 && median < ceil {
        let ym = y(median);
        s.push_str(&format!(
            "<line x1=\"{PAD_L}\" y1=\"{ym:.1}\" x2=\"{:.1}\" y2=\"{ym:.1}\" \
             stroke=\"#5a6478\" stroke-width=\"1\" stroke-dasharray=\"4 3\"/>\n\
             <text x=\"{:.1}\" y=\"{:.1}\" font-size=\"10\" \
             fill=\"#5a6478\">median {}</text>\n",
            PAD_L + plot_w,
            PAD_L + 4.0, ym - 3.0,
            fnum(median as f64),
        ));
    }
    // x ticks (same 4-label policy as the block bars)
    for t in plot::x_ticks(out, cols, n_src) {
        let x = PAD_L + (t.col as f32 + 0.5) * bw;
        s.push_str(&format!(
            "<text x=\"{x:.1}\" y=\"{:.1}\" text-anchor=\"middle\" \
             font-size=\"11\" fill=\"#5a6478\">{}</text>\n",
            SVG_H - 6.0,
            esc(&t.label),
        ));
    }
    s.push_str("</svg>\n");
    Some(s)
}

// ── orchestration ────────────────────────────────────────────────────────────

/// The deterministic file-drop pipeline as a report: pick_rune per file,
/// run it with `--json`, correlate when two or more files qualify, render
/// one HTML string. Shared by `olorin report` and (next) `/api/report`.
/// `files` is (display name, path). The returned summary is the CLI's
/// stderr table. No model, no safety scan — nothing here reaches an LLM,
/// and every derived string is HTML-escaped at render time.
pub fn build_report(
    files: &[(String, String)],
    version: &str,
) -> Result<(String, String), String> {
    if files.is_empty() {
        return Err("no files given".to_string());
    }
    let mut sections: Vec<ReportSection> = Vec::new();
    let mut summary = String::new();

    for (display, path) in files {
        let prefix = read_prefix(path, 8192);
        let Some(rune) = super::select::pick_rune(display, &prefix) else {
            summary.push_str(&format!("  {display:<20} → (no rune matched, skipped)\n"));
            continue;
        };
        let name = rune.name();
        let flags = super::select::default_args(name);
        let args = if flags.is_empty() {
            format!("--json {path}")
        } else {
            format!("{flags} --json {path}")
        };
        let result = rune.run(&args);
        let output = RuneOutput::from_json(result.answer.as_bytes())
            .map_err(|e| format!("{display}: rune output not parseable: {e}"))?;
        let note = if output.anomalies.is_empty() {
            format!("({} records)", output.totals.rows)
        } else {
            format!("({} records, {} spike(s))", output.totals.rows, output.anomalies.len())
        };
        summary.push_str(&format!("  {display:<20} → {name:<10} {note}\n"));
        sections.push(ReportSection {
            display: display.clone(),
            rune:    name.to_string(),
            output,
        });
    }
    if sections.is_empty() {
        return Err("no analyzable files (csv, jsonl, parquet, sql, log)".to_string());
    }

    let correlation = if files.len() >= 2 {
        let corr = super::eacorrelate::correlate_files(files);
        if corr.success && !corr.correlations.is_empty() {
            summary.push_str(&format!(
                "  {:<20} → {} finding(s)\n", "eacorrelate", corr.correlations.len(),
            ));
            Some(corr)
        } else {
            None
        }
    } else {
        None
    };

    Ok((render_report(&sections, correlation.as_ref(), version), summary))
}

/// First `max` bytes of a file for rune selection; empty on any error so
/// `pick_rune` falls back to extension-only routing.
fn read_prefix(path: &str, max: usize) -> Vec<u8> {
    use std::io::Read;
    let Ok(mut f) = std::fs::File::open(path) else { return Vec::new() };
    let mut buf = vec![0u8; max];
    match f.read(&mut buf) {
        Ok(n) => { buf.truncate(n); buf }
        Err(_) => Vec::new(),
    }
}

/// Minimal HTML escaping for file-derived strings.
fn esc(s: &str) -> String {
    let mut o = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => o.push_str("&amp;"),
            '<' => o.push_str("&lt;"),
            '>' => o.push_str("&gt;"),
            '"' => o.push_str("&quot;"),
            '\'' => o.push_str("&#39;"),
            _ => o.push(ch),
        }
    }
    o
}
